### ISSUE TITLE
Store the HP of NPCs - Suggestion

### ISSUE THREAD

**Issue by thebubbsy** [AnkouOSRS/npc-menu-hp#1]
I get this is written for barrage tasks, but this could specifically be fairly useful for Olm Hands during P3 when you're unsure of how much HP the mage/melee hand has left in solo and team raids. Could be very useful here as well to be able to right click and see how much HP is left before finishing off the other hand

**Comment by AnkouOSRS** [comment]
I agree this would make for a great enhancement, and as far as I know, it is doable. This along with the option to specify specific npcs for the plugin to work on will both go into the next update as long as nothing goes wrong.

**Comment by thebubbsy** [comment]
thanks beast

**Comment by AnkouOSRS** [comment]
This has been implemented and released in 1.1
