### ISSUE TITLE
Add menu color for monsters with unknown hp

### ISSUE THREAD

**Issue by equirs** [AnkouOSRS/npc-menu-hp#2]
I use this plugin to highlight certain npcs and would like to differentiate them between non-highlighted ones. Since the npc indicator highlights conflict with this plugin, it would be nice to have a separate configurable highlight color for monsters with an unknown hp count (and perhaps a toggle as well if this behavior is undesired).

**Comment by AnkouOSRS** [comment]
This seems like a nice feature to include since as you mentioned it conflicts with NPC indicators. I will look into adding this when I get the chance to do so!
