### ISSUE TITLE
Logs filled with error

### ISSUE THREAD

**Issue by joujoucoons** [AnkouOSRS/npc-menu-hp#9]
my logs folder is getting filled with error "2024-04-13 12:37:28 EEST [Client] ERROR com.monsterhp.MonsterHPOverlay - there was an error:java.lang.NullPointerException" it takes 10-20 gb of space after week of clearing

**Comment by AnkouOSRS** [comment]
Any additional details from the logs that might point to where this is coming from? I haven't seen it before.

**Comment by AnkouOSRS** [comment]
I see it's in the overlay but there should be a method name or a line number

**Comment by joujoucoons** [comment]
as i investigated this further it seems to be another plugin not this one sorry for the confusion

**Comment by AnkouOSRS** [comment]
No worries!
